import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import { signIn } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Church Backend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Church Backend</h1>
        <Button onClick={() => signIn()}>Sign in</Button>
      </main>
    </div>
  );
};

export default Home;
